name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print info
        run: echo "CI run on  at Fri Oct 31 11:13:20 CST 2025"
